spring.application.name=competition-management-system

#server
server.port=8080

#Database
spring.datasource.url=jdbc:postgresql:loclhost:5432/cms
spring.datasource.username=cms
spring.datasource.password=secure_cms

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Flyway
spring.flyway.enabled=true

#Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
